name: Service - Auth

on:
  workflow_dispatch:
    inputs:
      deploy_to:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: staging
      deploy_only:
        description: 'If true, skip test and build and run deployment only'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/_backend-service.yml
    with:
      service-name: auth-service
      service-path: services/auth-service
      docker-image-name: coop-auth
      container-app-name: ca-coop-dev-auth
      server-port: '8081'
      deploy_to: ${{ inputs.deploy_to || 'staging' }}
      deploy_only: ${{ inputs.deploy_only || false }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
