name: Service - Payment

on:
  workflow_dispatch:
    inputs:
      deploy_to:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: staging

permissions:
  id-token: write
  contents: read

jobs:
  pipeline:
    uses: ./.github/workflows/_backend-service.yml
    with:
      service-name: payment-service
      service-path: services/payment-service
      docker-image-name: coop-payment
      container-app-name: ca-coop-dev-payment
      server-port: '8083'
      deploy_to: ${{ inputs.deploy_to || 'staging' }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
