name: Release - Dev

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/**'
      - 'services/**'
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: release-dev
  cancel-in-progress: false

jobs:
  infrastructure:
    name: Infra - Terraform
    uses: ./.github/workflows/infrastructure.yml
    secrets: inherit

  auth:
    name: Service - Auth
    needs: infrastructure
    uses: ./.github/workflows/_backend-service.yml
    with:
      service-name: auth-service
      service-path: services/auth-service
      docker-image-name: coop-auth
      container-app-name: ca-coop-dev-auth
      server-port: '8081'
      deploy_to: staging
    secrets: inherit

  account:
    name: Service - Account
    needs: infrastructure
    uses: ./.github/workflows/_backend-service.yml
    with:
      service-name: account-service
      service-path: services/account-service
      docker-image-name: coop-account
      container-app-name: ca-coop-dev-account
      server-port: '8082'
      deploy_to: staging
    secrets: inherit

  payment:
    name: Service - Payment
    needs: account
    uses: ./.github/workflows/_backend-service.yml
    with:
      service-name: payment-service
      service-path: services/payment-service
      docker-image-name: coop-payment
      container-app-name: ca-coop-dev-payment
      server-port: '8083'
      deploy_to: staging
    secrets: inherit

  frontend:
    name: Web - Frontend
    needs: [auth, account, payment]
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
